name: smart_home_voice
description: Smart Home Voice Control App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  intl: ^0.19.0

flutter:
  uses-material-design: true
